# Generated by Django 3.2.3 on 2021-06-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PRODUCING_MANAGER', 'PRODUCING_MANAGER'), ('FOREMAN', 'FOREMAN'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='img/logo.png', upload_to='images/users/'),
        ),
    ]
