# Generated by Django 3.2.3 on 2021-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210603_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('WAREHOUSE_STAFF', 'WAREHOUSE_STAFF'), ('BUSINESS_STAFF', 'BUSINESS_STAFF'), ('SALES_STAFF', 'SALES_STAFF'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=50),
        ),
    ]
